BMK-349 check status of each benchmark, and fail (at the end) the overall app if one failed

diff --git a/hep-benchmark-suite b/hep-benchmark-suite
--- a/hep-benchmark-suite
+++ b/hep-benchmark-suite
@@ -21,6 +21,7 @@ source "$SOURCEDIR"/scripts/plugins.sh
 
 echo "export init_tests=$(date +%s)" >> ${TIMES_SOURCE_PATH}
 
+FAIL_BMKS=0
 GOOD_BMKS=0
 for b in $bmks
 do
@@ -28,13 +29,13 @@ do
   if [[ $b == 'kv' ]]; then
     echo "INFO: running KV..."
     # Launch in normal mode
-    run_kv "$TIMES_SOURCE_PATH" "$SOURCEDIR" || true
+    run_kv "$TIMES_SOURCE_PATH" "$SOURCEDIR" || FAIL_BMKS=$((FAIL_BMKS+1))
   elif [[ $b =~ "hepscore" ]]; then
-      run_hepscore || true 
+      run_hepscore || FAIL_BMKS=$((FAIL_BMKS+1))
   elif [[ $b =~ ^(hs06_(32|64))$ ]]; then
-      run_hs06 "$b" || true 
+      run_hs06 "$b" || FAIL_BMKS=$((FAIL_BMKS+1))
   elif [[ $b == "spec2017" ]]; then
-      run_spec2017 || true 
+      run_spec2017 || FAIL_BMKS=$((FAIL_BMKS+1))
   elif [[ $b == "hyper-benchmark" ]]; then
     echo "INFO: running hyper-benchmark..."
     export HYPER_BENCHMARK=1
@@ -82,4 +83,8 @@ done
 # Generate the report
 [[ $GOOD_BMKS -gt 0 ]] && run_report
 
-END=1
+# Fail if at least a benchmark failed
+[[ $FAIL_BMKS -gt 0 ]] && echo -e "Number of failed benchmarks is $FAIL_BMKS" && ENDSTATUS=1 && exit 1
+
+ENDSTATUS=0
+exit 0
